### ISSUE TITLE
Validar el proceso para incorporar cambios en Cloud Run

### ISSUE THREAD

**Issue by FvD** [datalatam/shiny_app_cloud_run#7]
Uno de los amigos en datalatam trato de seguir el ejemplo pero no logro que el trigger haga un nuevo despliegue con la nueva version. Hay que repetir el ejemplo para validar que esto sigue funcionando en Cloud Run. Veo que hay cambios en la interfaz de Google que quizas reflejan cambios en los procesos que arrancan por defecto.

**Comment by FvD** [comment]
Primero valido con lo que esta hoy en dia. Ojo que hay un Cloud Build Configuration file que no esta entre el codigo ejemplo pero se mantiene inline. Cuando revisé con la persona que trato de repetir los pasos, Google Cloud Run no incluyo un cloudbuild yaml file como este (parecia que era solo un hello-world sin el deploy step).

```yaml
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: webinario-datalatam
  _LABELS: gcb-trigger-id=05dcd72d-d434-4853-80c7-189c2327ad81
  _TRIGGER_ID: 05dcd72d-d434-4853-80c7-189c2327ad81
  _DEPLOY_REGION: us-central1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - webinario-datalatam
```

**Comment by FvD** [comment]
El resultado del ensayo en https://github.com/datalatam/shiny_app_cloud_run/pull/9 es:

![image](https://user-images.githubusercontent.com/2441145/198844964-8da56211-8cd9-4a19-9471-39103a73f84f.png)

Funciona bien, y muestra el cambio. Arranque un nuevo proceso en cloud build y veo que por defecto incluye el cloudbuild configuratoin file y parece ser igual con los pasos build - push - deploye

```yaml
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _LABELS: gcb-trigger-id=c7f87c69-8ed7-4ec1-98ca-6aa555a69fc4
  _TRIGGER_ID: c7f87c69-8ed7-4ec1-98ca-6aa555a69fc4
  _SERVICE_NAME: webinario-cloud-run-shiny
  _DEPLOY_REGION: us-east1
  _GCR_HOSTNAME: us.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - webinario-cloud-run-shiny
```
